// SF_LESSON_META — CATC CPL-IR Vol 05, 96 lessons
// Source: Course Manual Issue 02, Rev 00, Effective 20 Nov 2025
// type: 'Solo' → FI need not be free (but must not be on leave)
// type: 'SPIC' → treated same as Dual (FI must be free)
// type: 'Dual' → FI must be free within duty limits

window.SF_LESSON_META = {
  // ── Phase I — Basic General Handling ──────────────────────────────────────
  "CDGL 01": { n:1,  phase:1, durMin:60,  type:"Dual", title:"First Air Experience & Familiarization" },
  "CDGL 02": { n:2,  phase:1, durMin:60,  type:"Dual", title:"Effect of Controls" },
  "CDGL 03": { n:3,  phase:1, durMin:60,  type:"Dual", title:"Standard and Medium Turns" },
  "CDGL 04": { n:4,  phase:1, durMin:60,  type:"Dual", title:"Climb and Descent" },
  "CDGL 05": { n:5,  phase:1, durMin:75,  type:"Dual", title:"Turns in Various Configurations" },
  "CDGL 06": { n:6,  phase:1, durMin:75,  type:"Dual", title:"Basic UPRT (1) — Arrest Divergence / Avoid Spin" },
  "CDGL 07": { n:7,  phase:1, durMin:75,  type:"Dual", title:"Basic UPRT (2) — Flight Path Management" },
  "CDGL 08": { n:8,  phase:1, durMin:75,  type:"Dual", title:"Basic UPRT (3) — Stall Recognition & Recovery" },
  "CDGL 09": { n:9,  phase:1, durMin:75,  type:"Dual", title:"Simulated Forced Landing" },
  "CDGL 10": { n:10, phase:1, durMin:60,  type:"Dual", title:"Circuit, Take-Off and Landing (1)" },
  "CDGL 11": { n:11, phase:1, durMin:60,  type:"Dual", title:"Circuit, Take-Off and Landing (2)" },
  "CDGL 12": { n:12, phase:1, durMin:60,  type:"Dual", title:"Circuit, Take-Off and Landing (3)" },
  "CDGL 13": { n:13, phase:1, durMin:45,  type:"Dual", title:"Final Pre-Solo" },

  // ── Phase II — Solo Consolidation, Basic IFR & VFR Cross Country ──────────
  "CSGL 14":  { n:14, phase:2, durMin:20,  type:"Solo", title:"First Solo Flight" },
  "CDIL 15":  { n:15, phase:2, durMin:75,  type:"Dual", title:"Basic Instrument Flying (1) — Full Panel" },
  "CSGL 16":  { n:16, phase:2, durMin:45,  type:"Solo", title:"Solo Circuit" },
  "CDIL 17":  { n:17, phase:2, durMin:90,  type:"Dual", title:"Basic Instrument Flying (2) — Instrument Pattern & Steep Turns" },
  "CSGL 18":  { n:18, phase:2, durMin:75,  type:"Solo", title:"Solo General Handling" },
  "CDIL 19":  { n:19, phase:2, durMin:90,  type:"Dual", title:"Basic Instrument Flying (3) — Radio Navigation" },
  "CSGL 20":  { n:20, phase:2, durMin:75,  type:"Solo", title:"Solo General Handling" },
  "CDIL 21":  { n:21, phase:2, durMin:90,  type:"Dual", title:"Basic Instrument Flying (4) — Unusual Attitude / Partial Panel" },
  "CSGL 22":  { n:22, phase:2, durMin:75,  type:"Solo", title:"Solo General Handling" },
  "CDIL 23":  { n:23, phase:2, durMin:75,  type:"Dual", title:"Basic Instrument Flying (5) — Stall & Radio Nav" },
  "CSGL 24":  { n:24, phase:2, durMin:75,  type:"Solo", title:"Solo General Handling" },
  "CDIL 25":  { n:25, phase:2, durMin:90,  type:"Dual", title:"Basic Instrument Flying (6) — Limited Panel" },
  "CSGL 26":  { n:26, phase:2, durMin:75,  type:"Solo", title:"Solo General Handling" },
  "CDIL 27":  { n:27, phase:2, durMin:90,  type:"Dual", title:"Basic Instrument Flying (7) — Limited Panel & Stall" },
  "CSGL 28":  { n:28, phase:2, durMin:80,  type:"Solo", title:"Solo General Handling" },
  "CDXV 29":  { n:29, phase:2, durMin:90,  type:"Dual", title:"VFR Cross Country (1)" },
  "CSGL 30":  { n:30, phase:2, durMin:80,  type:"Solo", title:"Solo General Handling" },
  "CDXV 31":  { n:31, phase:2, durMin:90,  type:"Dual", title:"VFR Cross Country (2)" },
  "CDXV 32":  { n:32, phase:2, durMin:120, type:"Dual", title:"VFR Cross Country (3)" },

  // ── Phase III — Advanced XC, Night Flying & VFR Progress Test ─────────────
  "CSXV 33":  { n:33, phase:3, durMin:90,  type:"Solo", title:"First Solo VFR Cross Country" },
  "CDGL 34":  { n:34, phase:3, durMin:60,  type:"Dual", title:"General Handling Review (1) — Flight Path Management & Steep Turns" },
  "CDGL 35":  { n:35, phase:3, durMin:60,  type:"Dual", title:"General Handling Review (2) — Stall Recovery All Configs" },
  "CSPGL 36": { n:36, phase:3, durMin:75,  type:"SPIC", title:"SPIC General Handling (1) — Emergency & Abnormal Procedures" },
  "CSPGL 37": { n:37, phase:3, durMin:75,  type:"SPIC", title:"SPIC General Handling (2) — Instrument Pattern" },
  "CSPXV 38": { n:38, phase:3, durMin:120, type:"SPIC", title:"SPIC VFR Cross Country (1)" },
  "CSPXV 39": { n:39, phase:3, durMin:180, type:"SPIC", title:"SPIC VFR Cross Country (2)" },
  "CSPXV 40": { n:40, phase:3, durMin:180, type:"SPIC", title:"SPIC VFR Cross Country (3)" },
  "CSPXV 41": { n:41, phase:3, durMin:180, type:"SPIC", title:"SPIC VFR Cross Country (4) — Track Deviation Correction" },
  "CSPXV 42": { n:42, phase:3, durMin:180, type:"SPIC", title:"SPIC VFR Cross Country (5) — Consolidation" },
  "CSPXV 43": { n:43, phase:3, durMin:180, type:"SPIC", title:"SPIC VFR Cross Country (6) — Long-Range Validation" },
  "CSPXV 44": { n:44, phase:3, durMin:300, type:"SPIC", title:"SPIC VFR Cross Country (7) — Qualifying Flight ≥300 NM" },
  "CSXV 45":  { n:45, phase:3, durMin:300, type:"Solo", title:"Solo Long Cross Country ≥300 NM" },
  "CDNL 46":  { n:46, phase:3, durMin:60,  type:"Dual", title:"Dual Night Flying (1) — Night Circuits" },
  "CDNL 47":  { n:47, phase:3, durMin:60,  type:"Dual", title:"Dual Night Flying (2) — Night Traffic Pattern" },
  "CDNXC 48": { n:48, phase:3, durMin:60,  type:"Dual", title:"Dual Night Cross Country" },
  "CSNL 49":  { n:49, phase:3, durMin:60,  type:"Solo", title:"Solo Night (1) — Night Circuits" },
  "CSNL 50":  { n:50, phase:3, durMin:60,  type:"Solo", title:"Solo Night (2) — Night Circuit Consolidation" },
  "CSPGL 51": { n:51, phase:3, durMin:80,  type:"SPIC", title:"SPIC General Handling (3) — S&L, Turns, Climbs, Descents Review" },
  "CSPGL 52": { n:52, phase:3, durMin:80,  type:"SPIC", title:"SPIC General Handling (4) — Steep Turns, Slow/High-Speed Flight" },
  "CSPGL 53": { n:53, phase:3, durMin:80,  type:"SPIC", title:"SPIC General Handling (5) — Stall All Configs & Forced Landing" },
  "CSPGLC 54":{ n:54, phase:3, durMin:90,  type:"SPIC", title:"General Handling Progress Check (SPIC)" },
  "CSPXVC 55":{ n:55, phase:3, durMin:90,  type:"SPIC", title:"VFR Cross Country Progress Check (SPIC)" },

  // ── Phase IV — Instrument Flight (SIM + SE + ME) ──────────────────────────
  "CDIF(SIM) 56": { n:56, phase:4, durMin:120, type:"Dual", title:"IFR SIM (1) — ADF/VOR Intercept & Tracking" },
  "CDIF(SIM) 57": { n:57, phase:4, durMin:120, type:"Dual", title:"IFR SIM (2) — NDB Holding & NDB Approach" },
  "CDIF(SIM) 58": { n:58, phase:4, durMin:120, type:"Dual", title:"IFR SIM (3) — VOR Holding & VOR Approach" },
  "CDIF(SIM) 59": { n:59, phase:4, durMin:120, type:"Dual", title:"IFR SIM (4) — Localizer / ILS Approach" },
  "CDIF(SIM) 60": { n:60, phase:4, durMin:120, type:"Dual", title:"IFR SIM (5) — 2D/3D Approach Consolidation" },
  "CDIF(SIM) 61": { n:61, phase:4, durMin:120, type:"Dual", title:"IFR SIM (6) — Holdings & Segment Transitions" },
  "CDIF(SIM) 62": { n:62, phase:4, durMin:120, type:"Dual", title:"IFR SIM (7) — Full IFR Route with SID" },
  "CDIF(SIM) 63": { n:63, phase:4, durMin:120, type:"Dual", title:"IFR SIM (8) — Abnormal Scenarios" },
  "CDIF(SIM) 64": { n:64, phase:4, durMin:180, type:"Dual", title:"IFR SIM (9) — Missed Approach & Circling" },
  "CDIF(SIM) 65": { n:65, phase:4, durMin:180, type:"Dual", title:"IFR SIM (10) — Full IFR Mission Profile" },
  "CDIF(SIM) 66": { n:66, phase:4, durMin:180, type:"Dual", title:"IFR SIM (11) — Complex Scenario Decision-Making" },
  "CDIF(SIM) 67": { n:67, phase:4, durMin:180, type:"Dual", title:"IFR SIM (12) — Pre-Aircraft Readiness Validation" },
  "CDXI 68":  { n:68, phase:4, durMin:120, type:"Dual", title:"SE IFR XC (1) — Initial Aircraft Transfer from SIM" },
  "CDXI 69":  { n:69, phase:4, durMin:120, type:"Dual", title:"SE IFR XC (2) — Holdings & ATC Transitions" },
  "CDXI 70":  { n:70, phase:4, durMin:120, type:"Dual", title:"SE IFR XC (3) — IFR Departure & Full-Profile" },
  "CDXI 71":  { n:71, phase:4, durMin:120, type:"Dual", title:"SE IFR XC (4) — Multi-Leg Route Navigation" },
  "CDXI 72":  { n:72, phase:4, durMin:120, type:"Dual", title:"SE IFR XC (5) — Alternate Diversion Planning" },
  "CDXI 73":  { n:73, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (6) — GPS/RNAV Navigation" },
  "CDXI 74":  { n:74, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (7) — Missed Approach Procedures" },
  "CDXI 75":  { n:75, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (8) — High Workload Management" },
  "CDXI 76":  { n:76, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (9) — Abnormal IFR Scenarios" },
  "CDXI 77":  { n:77, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (10) — Flight Path & Fuel Management" },
  "CDXI 78":  { n:78, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (11) — Approach Minima & Decision" },
  "CDXI 79":  { n:79, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (12) — Complex Airspace Operations" },
  "CDXI 80":  { n:80, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (13) — Autonomous IFR Management" },
  "CDXI 81":  { n:81, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (14) — Pre-SPIC Consolidation" },
  "CDXI 82":  { n:82, phase:4, durMin:180, type:"Dual", title:"SE IFR XC (15) — SPIC Readiness Validation" },
  "CDGL 83":  { n:83, phase:4, durMin:90,  type:"Dual", title:"General Handling Review — Performance & UPRT (SE)" },
  "CDGL 84":  { n:84, phase:4, durMin:90,  type:"Dual", title:"General Handling Review — Stall & Upset Recovery (SE)" },
  "CSPXI 85": { n:85, phase:4, durMin:120, type:"SPIC", title:"SPIC IFR XC (1) — Independent IFR Basics" },
  "CSPXI 86": { n:86, phase:4, durMin:120, type:"SPIC", title:"SPIC IFR XC (2) — Complete IFR XC as SPIC" },
  "CSPXI 87": { n:87, phase:4, durMin:180, type:"SPIC", title:"SPIC IFR XC (3) — Multiple Approach Types" },
  "CSPXI 88": { n:88, phase:4, durMin:180, type:"SPIC", title:"SPIC IFR XC (4) — Diversion Decision-Making" },
  "CSPXI 89": { n:89, phase:4, durMin:180, type:"SPIC", title:"SPIC IFR XC (5) — Pre-Check Review" },
  "CSPXIC 90":{ n:90, phase:4, durMin:180, type:"SPIC", title:"SE SPIC IFR Progress Check" },
  "CMDIF(SIM) 91": { n:91, phase:4, durMin:60,  type:"Dual", title:"ME SIM (1) — ME Normal Operations" },
  "CMDIF(SIM) 92": { n:92, phase:4, durMin:60,  type:"Dual", title:"ME SIM (2) — Engine-Out Operations (OEI)" },
  "CMDGL 93": { n:93, phase:4, durMin:90,  type:"Dual", title:"ME Dual General Handling — Upset & Stall Recovery" },
  "CMDXV 94": { n:94, phase:4, durMin:90,  type:"Dual", title:"ME Dual VFR Cross Country" },
  "CMSPXI 95":{ n:95, phase:4, durMin:120, type:"SPIC", title:"ME SPIC IFR Cross Country" },
  "CMSPXIC 96":{ n:96, phase:4, durMin:120, type:"SPIC", title:"ME SPIC IFR Final Check" },
};

// Ordered groups for the lesson picker dropdown
window.SF_LESSON_GROUPS = [
  {
    label: "Phase I — Basic General Handling",
    codes: [
      "CDGL 01","CDGL 02","CDGL 03","CDGL 04","CDGL 05","CDGL 06","CDGL 07",
      "CDGL 08","CDGL 09","CDGL 10","CDGL 11","CDGL 12","CDGL 13",
    ],
  },
  {
    label: "Phase II — Solo Consolidation, Basic IFR & VFR XC",
    codes: [
      "CSGL 14","CDIL 15","CSGL 16","CDIL 17","CSGL 18","CDIL 19","CSGL 20",
      "CDIL 21","CSGL 22","CDIL 23","CSGL 24","CDIL 25","CSGL 26","CDIL 27",
      "CSGL 28","CDXV 29","CSGL 30","CDXV 31","CDXV 32",
    ],
  },
  {
    label: "Phase III — Advanced XC, Night Flying & VFR Progress Test",
    codes: [
      "CSXV 33","CDGL 34","CDGL 35","CSPGL 36","CSPGL 37",
      "CSPXV 38","CSPXV 39","CSPXV 40","CSPXV 41","CSPXV 42","CSPXV 43","CSPXV 44",
      "CSXV 45","CDNL 46","CDNL 47","CDNXC 48","CSNL 49","CSNL 50",
      "CSPGL 51","CSPGL 52","CSPGL 53","CSPGLC 54","CSPXVC 55",
    ],
  },
  {
    label: "Phase IV — Instrument Flight (SIM + SE + ME)",
    codes: [
      "CDIF(SIM) 56","CDIF(SIM) 57","CDIF(SIM) 58","CDIF(SIM) 59",
      "CDIF(SIM) 60","CDIF(SIM) 61","CDIF(SIM) 62","CDIF(SIM) 63",
      "CDIF(SIM) 64","CDIF(SIM) 65","CDIF(SIM) 66","CDIF(SIM) 67",
      "CDXI 68","CDXI 69","CDXI 70","CDXI 71","CDXI 72","CDXI 73","CDXI 74",
      "CDXI 75","CDXI 76","CDXI 77","CDXI 78","CDXI 79","CDXI 80","CDXI 81","CDXI 82",
      "CDGL 83","CDGL 84",
      "CSPXI 85","CSPXI 86","CSPXI 87","CSPXI 88","CSPXI 89","CSPXIC 90",
      "CMDIF(SIM) 91","CMDIF(SIM) 92","CMDGL 93","CMDXV 94",
      "CMSPXI 95","CMSPXIC 96",
    ],
  },
];
